steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/gcp-test/hello-world:1.0', '.' ]
images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/gcp-test/hello-world:1.0'
